### ISSUE TITLE
When an error happens in a before block, no screenshot is recorded

### ISSUE THREAD

**Issue by hybrist** [testiumjs/testium-mocha#9]

**Comment by aotarola** [comment]
I added a non-existent URL into the navigateTo method to make it fail, and no screenshot is taken.
```bash
  Super integration test
    on my cool test
      1) "before all" hook


  0 passing (2s)
  1 failing

  1) Super integration test on my cool test "before all" hook:
     Error: [execute("return (function () {\n        return $.fx.off = true;\n      }).apply(this, []);")] Error response status: 13, , UnknownError - An unknown server-side error occurred while processing the command. Selenium error: {"errorMessage":"Can't find variable: $","request":{"headers":{"Accept":"application/json","Connection":"keep-alive","Content-Length":"104","Content-Type":"application/json; charset=UTF-8","User-Agent":"admc/wd/1.2.0","host":"127.0.0.1:50940"},"httpVersion":"1.1","method":"POST","post":"{\"script\":\"return (function () {\\n        return $.fx.off = true;\\n      }).apply(this, []);\",\"args\":[]}","url":"/execute","urlParsed":{"anchor":"","query":"","file":"execute","directory":"/","path":"/execute","relative":"/execute","port":"","host":"","password":"","user":"","userInfo":"","authority":"","protocol":"","source":"/execute","queryKey":{},"chunks":["execute"]},"urlOriginal":"/session/6bfbaa30-4233-11e7-9d51-61627f3a0528/execute"}}
      at exports.newError (node_modules/grpn-test/node_modules/testium-driver-wd/node_modules/wd/lib/utils.js:145:13)
      at node_modules/grpn-test/node_modules/testium-driver-wd/node_modules/wd/lib/callbacks.js:75:19
      at node_modules/grpn-test/node_modules/testium-driver-wd/node_modules/wd/lib/webdriver.js:179:5
      at Request._callback (node_modules/grpn-test/node_modules/testium-driver-wd/node_modules/wd/lib/http-utils.js:88:7)
      at Request.self.callback (node_modules/grpn-test/node_modules/testium-driver-wd/node_modules/wd/node_modules/request/request.js:186:22)
      at Request.<anonymous> (node_modules/grpn-test/node_modules/testium-driver-wd/node_modules/wd/node_modules/request/request.js:1081:10)
      at IncomingMessage.<anonymous> (node_modules/grpn-test/node_modules/testium-driver-wd/node_modules/wd/node_modules/request/request.js:1001:12)
      at endReadableNT (_stream_readable.js:921:12)
```

**Comment by aaarichter** [comment]
as much as I wish for a screenshot to be recorded, mocha is not considering the before or after hooks as part of the tests specs. I looked at the `suiteData` but it lacks the error object with the necessary data for screenshot generation
